"use client";
import { motion } from "framer-motion";
import Link from "next/link";
import {
  Mail, Globe, Filter, ArrowRight, ArrowUpRight, CheckCircle,
  Monitor, Search, Bot, Download, CalendarClock, Radar, FileSpreadsheet
} from "lucide-react";
import type { ReactNode } from "react";

type Tool = {
  href: string;
  icon: ReactNode;
  name: string;
  tagline: string;
  description: string;
  badge: string;
  features: string[];
  comingSoon: boolean;
  label?: string;
  download?: boolean;
  cta?: string;
};

const tools: Tool[] = [
   {
    href:        "https://mailreplyai.vercel.app",
    label:       "New",
    icon:        <Bot size={24} />,
    name:        "MailReply AI",
    tagline:     "Email & WhatsApp Web AI assistant",
    description: "Read conversations and generate instant replies for emails and WhatsApp messages. Generated by Anil Kumar, it helps you respond faster and smarter.",
    badge:       "NEW",
    features:    ["AI-powered replies", "Real-time processing", "Supports Email & WhatsApp Web"],
    comingSoon:  false,
  },
  {
    href:        "/tools/gsc-crawl-check",
    label:       "New",
    icon:        <CalendarClock size={24} />,
    name:        "GSC Last Crawl Checker",
    tagline:     "Bulk last Google crawl date & index status",
    description: "Paste up to 100 URLs and pull each page's last Google Search Console crawl date and index status live, with pause/resume controls and CSV export.",
    badge:       "NEW",
    features:    ["Up to 100 URLs", "Live crawl dates", "CSV export"],
    comingSoon:  false,
  },
  {
    href:        "/tools/searchops-studio",
    label:       "New",
    icon:        <Monitor size={24} />,
    name:        "SearchOps Studio",
    tagline:     "All-in-one SEO desktop app for Windows",
    description: "A powerful desktop toolkit for SEO pros — crawl & index audits, rank tracking, broken-link scans, AI-visibility, content tools, and bulk reports, all running natively on your PC.",
    badge:       "NEW",
    features:    ["Windows .exe installer", "Runs 100% on your PC", "Bulk & batch processing"],
    comingSoon:  false,
  },
  {
    href:        "/tools/rank-radar",
    label:       "New",
    icon:        <Radar size={24} />,
    name:        "Rank Radar",
    tagline:     "Google rank tracker desktop app",
    description: "Track true Google rankings with city-level positions, personalization off, and organic-only results, exactly as a real searcher sees them.",
    badge:       "NEW",
    features:    ["City-level rankings", "Personalization off", "Windows .exe installer"],
    comingSoon:  false,
  },
  {
    href:        "/tools/domain-insights",
    icon:        <Search size={24} />,
    name:        "Domain Insights",
    tagline:     "DA/DR, traffic rank & SEO - free",
    description: "Enter any domain to get authority score, global traffic rank, estimated visits, domain age, DNS, and a full on-page SEO health check - sourced from open datasets, no sign-up.",
    badge:       "NEW",
    features:    ["Authority & rank", "DNS + WHOIS", "On-page SEO audit"],
    comingSoon:  false,
  },
  {
    href:        "/tools/email-checker",
    icon:        <Mail size={24} />,
    name:        "Email Utilization Checker",
    tagline:     "Know exactly which emails are unused",
    description: "Compare master email lists against utilized sets. Find duplicates, unused addresses, and get instant copy-ready results.",
    badge:       "LIVE",
    features:    ["Cache to localStorage", "Quick-check mode", "Duplicate detection"],
    comingSoon:  false,
  },
  {
    href:        "/tools/number-generator",
    icon:        <Globe size={24} />,
    name:        "Global Number Generator",
    tagline:     "Random phone numbers for 60+ countries",
    description: "Generate realistic, country-formatted phone numbers worldwide. Search, filter, animate and copy in one click.",
    badge:       "LIVE",
    features:    ["60+ countries", "Rolling animation", "Generate all at once"],
    comingSoon:  false,
  },
  {
    href:        "/tools/domain-distiller",
    icon:        <Filter size={24} />,
    name:        "Domain Distiller",
    tagline:     "Extract root domains from raw logs",
    description: "Paste messy log data and instantly extract, deduplicate and export clean domain lists. Regex-powered, zero server calls.",
    badge:       "LIVE",
    features:    ["Regex engine", "Deduplication", "Download .txt"],
    comingSoon:  false,
  },
  {
    href:        "/tools/ranking-report-filter",
    label:       "New",
    icon:        <FileSpreadsheet size={24} />,
    name:        "Ranking Report Filter",
    tagline:     "Excel macro to clean rank-tracking exports",
    description: "A ready-to-use VBA macro that filters a keyword ranking report — keeps improved and stable positions, drops worsened and non-ranking rows. Copy or download the .bas.",
    badge:       "NEW",
    features:    ["One-click VBA macro", "Copy or .bas download", "Keeps only gains"],
    comingSoon:  false,
  }
];

const readouts = [
  { n: String(tools.length), l: "tools in the suite" },
  { n: "0", l: "sign-ups required" },
  { n: "100%", l: "free · no tracking" },
];

function toolKind(t: (typeof tools)[number]) {
  if (t.download) return { label: "Windows app", dot: "#c9a84c" };
  if (/^https?:\/\//.test(t.href)) return { label: "External", dot: "#37506c" };
  return { label: "Web tool", dot: "#16a34a" };
}

/* radar-sweep console motif — the one orchestrated motion on the page */
function RadarConsole() {
  return (
    <div className="relative w-full max-w-[340px] aspect-square mx-auto">
      <svg viewBox="0 0 200 200" className="w-full h-full">
        <defs>
          <radialGradient id="rd-core" cx="50%" cy="50%" r="50%">
            <stop offset="0%" stopColor="#c9a84c" stopOpacity="0.16" />
            <stop offset="70%" stopColor="#c9a84c" stopOpacity="0" />
          </radialGradient>
          <linearGradient id="rd-sweep" x1="0" y1="0" x2="1" y2="1">
            <stop offset="0%" stopColor="#f2d67e" stopOpacity="0.55" />
            <stop offset="100%" stopColor="#f2d67e" stopOpacity="0" />
          </linearGradient>
        </defs>
        <circle cx="100" cy="100" r="92" fill="url(#rd-core)" />
        {[34, 60, 86].map((r) => (
          <circle key={r} cx="100" cy="100" r={r} fill="none" stroke="#c9a84c" strokeOpacity="0.22" strokeWidth="1" />
        ))}
        <line x1="100" y1="8" x2="100" y2="192" stroke="#c9a84c" strokeOpacity="0.14" strokeWidth="1" />
        <line x1="8" y1="100" x2="192" y2="100" stroke="#c9a84c" strokeOpacity="0.14" strokeWidth="1" />
        <g
          className="radar-sweep"
          style={{ transformOrigin: "100px 100px", transformBox: "view-box" }}
        >
          <path d="M100 100 L100 12 A88 88 0 0 1 176 58 Z" fill="url(#rd-sweep)" />
          <line x1="100" y1="100" x2="100" y2="12" stroke="#f2d67e" strokeOpacity="0.7" strokeWidth="1.4" />
        </g>
        {[
          { cx: 132, cy: 74, d: 0 },
          { cx: 74, cy: 128, d: 1.3 },
          { cx: 138, cy: 132, d: 2.1 },
        ].map((b, i) => (
          <motion.circle
            key={i}
            cx={b.cx}
            cy={b.cy}
            r="3"
            fill="#f2d67e"
            animate={{ opacity: [0.2, 1, 0.2], scale: [0.8, 1.3, 0.8] }}
            transition={{ duration: 2.4, repeat: Infinity, delay: b.d, ease: "easeInOut" }}
          />
        ))}
        <circle cx="100" cy="100" r="3.5" fill="#f2d67e" />
      </svg>
    </div>
  );
}

export default function Home() {
  return (
    <div className="min-h-screen">
      {/* ── Hero: radar console ── */}
      <section className="px-4 sm:px-6 pt-10 pb-14">
        <motion.div
          initial={{ opacity: 0, y: 22 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.7, ease: [0.2, 0.7, 0.2, 1] }}
          className="max-w-[1200px] mx-auto relative overflow-hidden rounded-[28px] border border-white/10"
          style={{ background: "linear-gradient(160deg, #0c0f16, #141a26)" }}
        >
          {/* engineered texture */}
          <div
            className="absolute inset-0 opacity-[0.5] pointer-events-none"
            style={{
              backgroundImage:
                "radial-gradient(rgba(201,168,76,0.10) 1px, transparent 1px)",
              backgroundSize: "26px 26px",
              maskImage: "radial-gradient(120% 100% at 100% 0%, #000 20%, transparent 75%)",
              WebkitMaskImage: "radial-gradient(120% 100% at 100% 0%, #000 20%, transparent 75%)",
            }}
          />

          <div className="relative grid lg:grid-cols-[1.15fr_0.85fr] gap-8 p-8 sm:p-12 lg:p-14 items-center">
            {/* copy */}
            <div>
              <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full border border-white/10 bg-white/[0.04] mb-7">
                <span className="relative flex h-2 w-2">
                  <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-green-400 opacity-60" />
                  <span className="relative inline-flex rounded-full h-2 w-2 bg-green-400" />
                </span>
                <span className="text-xs font-medium text-slate-300 font-grotesk">All systems live</span>
              </div>

              <h1 className="font-grotesk font-extrabold tracking-tight text-white text-4xl sm:text-5xl lg:text-[3.4rem] leading-[1.04] mb-5">
                Your search operations,
                <br className="hidden sm:block" /> in one console.
              </h1>

              <p className="text-slate-300/90 text-base sm:text-lg leading-relaxed max-w-xl mb-9">
                Domain intelligence, crawl tracking, rank checks, and report cleanup — the tools SEO
                teams reach for, tuned for speed and free to run.
              </p>

              <div className="flex flex-col sm:flex-row gap-3 mb-11">
                <a href="#tools">
                  <motion.button whileHover={{ y: -2 }} whileTap={{ scale: 0.98 }} className="btn-primary px-7 py-3.5 text-sm w-full sm:w-auto flex items-center justify-center gap-2">
                    Browse the toolkit
                    <ArrowRight size={16} />
                  </motion.button>
                </a>
                <Link href="/tools/domain-insights">
                  <motion.button
                    whileHover={{ y: -2 }} whileTap={{ scale: 0.98 }}
                    className="px-7 py-3.5 text-sm w-full sm:w-auto flex items-center justify-center gap-2 rounded-xl font-grotesk font-medium text-white border border-white/15 bg-white/[0.03] hover:bg-white/[0.07] hover:border-white/25 transition-colors"
                  >
                    <Search size={15} /> Try Domain Insights
                  </motion.button>
                </Link>
              </div>

              {/* instrument readouts */}
              <div className="grid grid-cols-3 max-w-md border-t border-white/10 pt-6">
                {readouts.map((r, i) => (
                  <div key={r.l} className={i > 0 ? "pl-5 border-l border-white/10" : ""}>
                    <div className="font-mono text-2xl sm:text-3xl font-semibold text-white leading-none">{r.n}</div>
                    <div className="text-[11px] text-slate-400 mt-1.5 leading-tight">{r.l}</div>
                  </div>
                ))}
              </div>
            </div>

            {/* radar */}
            <div className="hidden lg:block">
              <RadarConsole />
            </div>
          </div>
        </motion.div>
      </section>

      {/* ── Tools ── */}
      <section id="tools" className="px-4 sm:px-6 pb-24 scroll-mt-20">
        <div className="max-w-[1200px] mx-auto">
          <div className="flex items-end justify-between flex-wrap gap-3 mb-8">
            <h2 className="text-2xl sm:text-3xl font-grotesk font-bold text-theme-text">The toolkit</h2>
            <p className="text-sm text-theme-muted">Open one and start working — no sign-up, no tracking.</p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-5">
            {tools.map((tool, i) => {
              const kind = toolKind(tool);
              return (
                <div key={i} className="relative p-6 group card-base card-hover flex flex-col">
                  {/* status channel */}
                  <div className="flex items-center justify-between mb-5">
                    <span className="inline-flex items-center gap-2 text-[11px] font-medium text-theme-muted font-grotesk">
                      <span className="w-1.5 h-1.5 rounded-full" style={{ background: kind.dot }} />
                      {kind.label}
                    </span>
                    {tool.label && (
                      <span className="text-[10px] font-bold text-theme-gold-deep bg-theme-gold/10 border border-theme-gold/25 rounded-full px-2 py-0.5 font-grotesk">
                        {tool.label}
                      </span>
                    )}
                  </div>

                  {/* icon tile */}
                  <div
                    className={`w-12 h-12 rounded-xl flex items-center justify-center mb-4 ${
                      tool.download
                        ? "bg-gradient-gold text-[#1b1403] shadow-gold"
                        : "bg-theme-surface-2 text-theme-gold border border-theme-line"
                    }`}
                  >
                    {tool.icon}
                  </div>

                  <h3 className="text-lg font-grotesk font-bold text-theme-text mb-1 group-hover:text-theme-gold-deep transition-colors">
                    {tool.name}
                  </h3>
                  <p className="text-[13px] font-medium text-theme-gold-deep mb-2.5">{tool.tagline}</p>
                  <p className="text-sm text-theme-muted leading-relaxed mb-5">{tool.description}</p>

                  <ul className="space-y-1.5 mb-6">
                    {tool.features.map((f, j) => (
                      <li key={j} className="flex items-center gap-2 text-[13px] text-theme-text/90">
                        <CheckCircle size={13} className="text-theme-gold flex-shrink-0" />
                        {f}
                      </li>
                    ))}
                  </ul>

                  {/* CTA pinned to bottom */}
                  <div className="mt-auto">
                    {tool.download ? (
                      <a href={tool.href} download className="block">
                        <button className="btn-primary w-full px-4 py-2.5 text-sm flex items-center justify-center gap-2">
                          {tool.cta ?? "Download"} <Download size={15} />
                        </button>
                      </a>
                    ) : (
                      <Link href={tool.href} className="block">
                        <button className="btn-secondary w-full px-4 py-2.5 text-sm flex items-center justify-center gap-2 group/btn">
                          {/^https?:\/\//.test(tool.href) ? "Open" : "Open tool"}
                          {/^https?:\/\//.test(tool.href) ? (
                            <ArrowUpRight size={15} className="transition-transform group-hover/btn:translate-x-0.5 group-hover/btn:-translate-y-0.5" />
                          ) : (
                            <ArrowRight size={15} className="transition-transform group-hover/btn:translate-x-0.5" />
                          )}
                        </button>
                      </Link>
                    )}
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </section>
    </div>
  );
}
